import { Component, Inject, Optional } from '@angular/core';
import { CommonModule } from '@angular/common';

import { Category } from '../shared/models/category.model';
import { CartService } from '../cart/services/cart.service';
import { ConfigOptionsService } from '../core/services/config-options.service';
import { ConstantsServiceToken } from '../core/services/constants.service';
import { ConstantsModel } from '../core/models/constants.model';
import { GeneratedStringToken } from '../core/services/generator.service';
import { LocalStorageService } from '../core/services/local-storage.service';

@Component({
  selector: 'app-first',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './first.component.html',
  styleUrls: ['./first.component.scss']
})
export class FirstComponent {
  name: string = "Some unique name";
  description: string = "Some fascinating description";
  price: number = 3.14;
  category: Category = Category.Health;
  isAvailable: boolean = true;
  elements: string[] = ["resplendent", "ineffable", "serendipitous", "(words generated by ChatGPT)"];

  constructor (
    @Optional() private cartService: CartService,
    private configOptionsService: ConfigOptionsService,
    @Inject(ConstantsServiceToken) private constantsModel: ConstantsModel,
    @Inject(GeneratedStringToken) private generator: string,
    private localStorageService: LocalStorageService
  ) { }
}
