import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

import { Category } from '../shared/models/category.model';

@Component({
  selector: 'app-first',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './first.component.html',
  styleUrls: ['./first.component.scss']
})
export class FirstComponent {
  name: string = "Some unique name";
  description: string = "Some fascinating description";
  price: number = 3.14;
  category: Category = Category.Health;
  isAvailable: boolean = true;
  elements: string[] = ["resplendent", "ineffable", "serendipitous", "(words generated by ChatGPT)"];
}
